#!/bin/bash

#should I do this on startvnc?
vglclient &

cat > ~/.gtkrc-2.0 << EOF
style "xfce-panel-window-style"
{
  XfcePanelWindow::autohide-size = 3
}
EOF

XFCE_PANEL_MIGRATE_DEFAULT=true startxfce4 &

#not sure where this needs to be.. but maybe doesn't matter? without this, fsleyes popups
export FSLDIR=/

#fslview can only handle 1 image?
vglrun fsleyes `find /input -name *.nii.gz` &
pid=$!
echo $pid > /fsleyes.pid

#maximize fsleyes
sleep 5
id=`wmctrl -pl | grep " $pid " | cut -f 1 -d " "`
echo $id > /id.txt
wmctrl -i -r $id -b add,fullscreen
